server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://192.168.10.41:3306/db_ctdigitech?serverTimezone=UTC
      url: jdbc:mysql://172.16.30.88:3306/db_ctdigitech?serverTimezone=UTC
      username: root
      password: root@123!

#Started Mybatis plus auto increment & running log
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
